<a href="https://colab.research.google.com/github/jjhbk/AI_course/blob/main/chap1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print("Hello world \n jathin \n jagannath ");

Hello world 
 jathin 
 jagannath 


In [7]:
x=2;
y=5;
x=pow(x,y);
print (x);



32


In [12]:
import numpy as np 
nparray= np.zeros((5,5));
print(nparray);


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [18]:
def divisible(x) :
   if x%3 == 0:
      print("number divisble by 3");
   else:
       print ("number not divisible ");

divisible(130);


number not divisible 


In [24]:
def fact_for(x):
  j=1;
  for i in range (1,x+1):
    j=j*i;
  print(j);

  return j;
def fact_while(x):
  j=1;
  while(x>1):
    j=j*x;
    x=x-1;
  print(j);
  return j;
  
  
fact_for(5);
fact_while(4);

  




120
24


In [29]:
import math as math
def distance(x1,y1,x2,y2):
  dist= math.sqrt((x2-x1)**2+(y2-y1)**2);
  print(dist);

distance(2,3,4,5);

2.8284271247461903


In [31]:
class car():
  def __init__(self,Vmin,Acc):
    self.Vmin= Vmin;
    self.Acc= Acc;
  def time(self,Vmax):
    time=(Vmax - self.Vmin)/self.Acc;
    print(time);

car1 = car(2,3);
car1.time(50);


  

16.0
