<a href="https://colab.research.google.com/github/jjhbk/AI_course/blob/main/QLeaerning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np 
gamma = 0.75;
alpha=0.9;
location_to_state={'A':0,'B':1,'C':2,'D':3,'E':4,'F':5,'G':6,'H':7,'I':8,'J':9,'K':10,'L':11};
actions=[0,1,2,3,4,5,6,7,8,9,10,11];
R=np.array([[0,1,0,0,0,0,0,0,0,0,0,0],
[1,0,1,0,0,1,0,0,0,0,0,0],
[0,1,0,0,0,0,1,0,0,0,0,0],
[0,0,0,0,0,0,0,1,0,0,0,0],
[0,0,0,0,0,0,0,0,1,0,0,0],
[0,1,0,0,0,0,0,0,0,1,0,0],
[0,0,1,0,0,0,1000,1,0,0,0,0],
[0,0,0,1,0,0,1,0,0,0,0,1],
[0,0,0,0,1,0,0,0,0,1,0,0],
[0,0,0,0,0,1,0,0,1,0,1,0],
[0,0,0,0,0,0,0,0,0,1,0,1],
[0,0,0,0,0,0,0,1,0,0,1,0]]);
Q=np.array(np.zeros([12,12]));
for i in range(1000):
  current_state= np.random.randint(0,12);
  playable_actions= [];
  for j in range (12):
    if R[current_state,j] > 0:
      playable_actions.append(j);
  next_state=np.random.choice(playable_actions);
  TD = R[current_state, next_state] + gamma * Q[next_state,np.argmax(Q[next_state,])] - Q[current_state, next_state];
  Q[current_state, next_state] = Q[current_state, next_state] +alpha * TD;
 # TD=R[current_state,next_state]+gamma*Q[current_state,np.argmax(Q[next_state,])-Q[current_state,next_state]];
  #Q[current_state,next_state]=Q[current_state,next_state]+alpha*TD;
print("Q-values:")
print(Q.astype(int));

Q-values:
[[   0 1689    0    0    0    0    0    0    0    0    0    0]
 [1267    0 2250    0    0 1267    0    0    0    0    0    0]
 [   0 1688    0    0    0    0 2999    0    0    0    0    0]
 [   0    0    0    0    0    0    0 2250    0    0    0    0]
 [   0    0    0    0    0    0    0    0  714    0    0    0]
 [   0 1688    0    0    0    0    0    0    0  951    0    0]
 [   0    0 2250    0    0    0 3999 2250    0    0    0    0]
 [   0    0    0 1689    0    0 2999    0    0    0    0 1688]
 [   0    0    0    0  536    0    0    0    0  951    0    0]
 [   0    0    0    0    0 1267    0    0  710    0 1267    0]
 [   0    0    0    0    0    0    0    0    0  951    0 1689]
 [   0    0    0    0    0    0    0 2250    0    0 1267    0]]


In [ ]:

for i in range(1000):
current_state = np.random.randint(0,12)
playable_actions = []
for j in range(12):
if R[current_state, j] > 0:
playable_actions.append(j)
next_state = np.random.choice(playable_actions)
TD = R[current_state, next_state] + gamma * Q[next_state,
np.argmax(Q[next_state,])] - Q[current_state, next_state]
Q[current_state, next_state] = Q[current_state, next_state] +
alpha * TD

# New Section